name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Deploy
      env:
        CI: true
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: npm run deploy --  --cname "aqua.samnyan.icu" --name="samnyan" --email=4137880+samnyan@users.noreply.github.com
